server:
  port: 8084

spring:
  application:
    name: projetolei-service
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
